name: Build and Deploy Nginx to AWS ECR

on:
  push:
    branches:
      - main
      - feature/*

env:
  AWS_REGISTRY: 375866976303.dkr.ecr.us-east-1.amazonaws.com/reg-app
  AWS_REGION: us-east-1
  TAG_NAME: v1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
        
    - name: Build Docker Image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ env.AWS_REGISTRY }}/nginx:${{ env.TAG_NAME }}

    - name: Login to Amazon ECR       
      id: login-ecr
      run: aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ env.AWS_REGISTRY }}

    - name: Push to AWS ECR
      uses: aws-actions/amazon-ecr-push@v1
      with:
        region: ${{ env.AWS_REGION }}
        registry-url: ${{ env.AWS_REGISTRY }}
        tags: nginx:${{ env.TAG_NAME }}