name: Build Nginx Image and Push Image to AWS ECR

on:
  push:
    branches:
      - main
      - feature/*

env:
  AWS_REGISTRY: 375866976303.dkr.ecr.us-east-1.amazonaws.com/reg-app
  AWS_REGION: us-east-1
  TAG_NAME: v1
  ECR_REPOSITORY: reg-app

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR       
      id: login-ecr
      run: aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ env.AWS_REGISTRY }}

    - name: Build Docker Image
      run: |
        docker build -f Dockerfile -t ${{ env.AWS_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ env.TAG_NAME }} .

    - name: Push Docker image to Amazon ECR
      run: |
          docker push ${{ env.AWS_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ env.TAG_NAME }}